/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import model.Caja;

/**
 *
 * @author martin.ramirez
 */
public class Reto4 extends javax.swing.JFrame {
double precio;
    
    /**
     * Creates new form Reto4
     */
    public Reto4() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtEPS = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbAfiliado = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbNivel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblValortotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        rbtH = new javax.swing.JRadioButton();
        rbtP = new javax.swing.JRadioButton();
        rbtG = new javax.swing.JRadioButton();
        cmbPrecio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("VALOR EPS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel5.setText("Documento del Afiliado: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setText("Nombre del Afiliado: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel7.setText("Precio inicial del Examen: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        cmbAfiliado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Tipo Afiliado", "- Beneficiario", "- Cotizante" }));
        cmbAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAfiliadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 120, -1));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Categoria", "- A", "- B" }));
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, -1));

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Nivel", "- 1", "- 2" }));
        getContentPane().add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, -1));

        jLabel10.setText("Valor Total: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        lblValortotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblValortotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 140, 20));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 110, -1));

        txtDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, -1));

        bgtEPS.add(rbtH);
        rbtH.setText("EPS Hasta Morir");
        rbtH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHActionPerformed(evt);
            }
        });
        getContentPane().add(rbtH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        bgtEPS.add(rbtP);
        rbtP.setText("EPS Pior es na");
        getContentPane().add(rbtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        bgtEPS.add(rbtG);
        rbtG.setText("EPS De guatemala pa guate pior");
        getContentPane().add(rbtG, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        getContentPane().add(cmbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seguro-de-salud.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 542));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     double precio=Integer.parseInt(cmbPrecio.getSelectedItem().toString());
     double vlrPagar=0;
     
       
       if (rbtH.isSelected()){
           int nivel = Integer.parseInt(JOptionPane.showInputDialog("Digite nivel"+
                                                                    "\n1"+
                                                                    "\n2"));
           lblValortotal=caja.valorPagar(nivel, cmbPrecio);
       }
       else {if (rbtP.isSelected()){
          String categoria=JOptionPane.showInputDialog("Ingrese categoria"+
                                                       "\nA"+
                                                        "\nB").toUpperCase(); 
       lblValortotal=caja.valorPagar(categoria, cmbPrecio);
           }
       else{ if(rbtG.isSelected()){
           double salario = Double.parseDouble(JOptionPane.showInputDialog("Salario basico cotizante"));
           lblValortotal=caja.valorPagar(salario, cmbPrecio);
           }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtDocumento.setText("");
        txtNombre.setText("");
        lblValortotal.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void rbtHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHActionPerformed
        // TODO add your handling code here:
        if(rbtH.isSelected()){
            cmbCategoria.setVisible(false);
            cmbNivel.setVisible(false);
            cmbAfiliado.setVisible(true);}
        else {if(rbtP.isSelected()){ 
            cmbAfiliado.setVisible(false);
            cmbCategoria.setVisible(false);
            cmbNivel.setVisible(true); }}
    }//GEN-LAST:event_rbtHActionPerformed

    private void cmbAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAfiliadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reto4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtEPS;
    private javax.swing.JComboBox<String> cmbAfiliado;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JComboBox<String> cmbPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblValortotal;
    private javax.swing.JRadioButton rbtG;
    private javax.swing.JRadioButton rbtH;
    private javax.swing.JRadioButton rbtP;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
}